# Info
title: My Website
description: This will include AI, LLM fine tuning, programming, math, statisics, etc.
theme: just-the-docs

url: https://avcode-exe.github.io/

# Plugins
plugins:
  - jekyll-default-layout
